function mexbuild_stereo_sgbm()

mex mex_stereo_sgbm.cpp ...
    -I'C:\Documents and Settings\tbailey\My Documents\Utilities\cpp_libraries\opencv\build\include' ...
    -L'C:\Documents and Settings\tbailey\My Documents\Utilities\cpp_libraries\opencv\build\x86\vc9\lib' ...
    -lopencv_core244 -lopencv_calib3d244
