function mexbuild_sift_test()

mex mex_sift_test.cpp ...
    -I'C:\Documents and Settings\tbailey\My Documents\Utilities\cpp_libraries\opencv\build\include' ...
    -L'C:\Documents and Settings\tbailey\My Documents\Utilities\cpp_libraries\opencv\build\x86\vc9\lib' ...
    -lopencv_highgui244 -lopencv_core244 -lopencv_features2d244 -lopencv_nonfree244

% -lANN -DWIN32 -DNDEBUG
