function mexbuild_image_read()

mex mex_image_read.cpp ...
    -I'C:\Documents and Settings\tbailey\My Documents\Utilities\cpp_libraries\opencv\build\include' ...
    -L'C:\Documents and Settings\tbailey\My Documents\Utilities\cpp_libraries\opencv\build\x86\vc9\lib' ...
    -lopencv_highgui244 -lopencv_core244

% -lANN -DWIN32 -DNDEBUG
